--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "EBCC"."LOAD_CONTROL" (
		"FILE_NAME" CHAR(100) NOT NULL,
		"TABLE" CHAR(100) NOT NULL,
		"FILE_TYPE" CHAR(6) NOT NULL,
		"CODE_PAGE" CHAR(6) NOT NULL,
		"REC_COUNT" INTEGER NOT NULL,
		"SEQ_NUM" INTEGER NOT NULL,
		"HASH_TOT" DECIMAL(31 , 2) DEFAULT 0,
		"CREATE_TS" TIMESTAMP DEFAULT CURRENT TIMESTAMP
	)
	DATA CAPTURE NONE;

