SELECT DISTINCT UNIQUE_ID,COMPANY_ID FROM DB2ENT.USER_SCOPE WHERE APPLICATION='EBCC' EXCEPT SELECT UNIQUE_ID,COMPANY_ID FROM DB2ENT.USER_ENTITLEMENT WHERE APPLICATION='EBCC'

UPDATE :schema.USER_SCOPE SET MODIFY_BY ='Reval Scope Cleanup' WHERE UNIQUE_ID=':uniqueId' AND COMPANY_ID=:companyId AND APPLICATION=':applicationName'

SELECT UNIQUE_ID,EMAIL_ADDRESS,MANAGER_EMAIL_ADDRESS FROM db2ent.INTUSER_LOOKUP WHERE APPLICATION='EBCC'