SELECT DISTINCT
       O_LETTER.CUSTOMER_NAME,
       O_LETTER.OFFER_LETTER_NUM,
       O_LETTER.COUNTRY_CODE,
       IN_HE.TPID_CODE,
       IN_HE.VENDOR_NUM,
       IN_HE.INVOICE_NUM,
       IN_HE.INVOICE_DATE,
       IN_HE.CREATE_TIMESTAMP,
       IN_HE.TOTAL_INVOICE_AMT,
       IN_DE.INV_DTL_LINE_NUM, 
       IN_DE.PURCHASE_ORDER_NUM, 
       IN_DE.MACHINE_TYPE, 
       IN_DE.MACHINE_MODEL, 
       IN_DE.MES_NUM, 
       IN_DE.ITEM_DESCRIPTION, 
       IN_DE.MFR_SERIAL_NUM, 
       IN_DE.UNIT_PRICE, 
       IN_DE.MFR_PART_NUM, 		
       IN_DE.INV_DTL_LINE_NUM,
       IN_AD1.CUSTOMER_NUM AS SHIP_CUST_NO, 
       IN_AD1.CUSTOMER_NAME AS SHIP_NAME, 
       IN_AD1.ADDRESS_LINE1 AS SHIP_ADDR1, 
       IN_AD1.ADDRESS_LINE2 AS SHIP_ADDR2, 
       IN_AD1.ADDRESS_LINE3 AS SHIP_CITY, 
       IN_AD1.ADDRESS_LINE4 AS SHIP_STATE, 
       IN_AD1.ADDRESS_LINE5 AS SHIP_ZIP,

       CASE WHEN IN_AD2.CUSTOMER_NUM IS NOT NULL 
               THEN IN_AD2.CUSTOMER_NUM
               ELSE IN_AD1.CUSTOMER_NUM
       END AS BILL_CUST_NUM,
       CASE WHEN IN_AD2.CUSTOMER_NUM IS NOT NULL 
               THEN IN_AD2.CUSTOMER_NAME 
               ELSE IN_AD1.CUSTOMER_NAME
       END AS BILL_CUST_NAME,
       CASE WHEN IN_AD2.CUSTOMER_NUM IS NOT NULL 
               THEN IN_AD2.ADDRESS_LINE1
               ELSE IN_AD1.ADDRESS_LINE1 
       END AS BILL_ADDR1,
       CASE WHEN IN_AD2.CUSTOMER_NUM IS NOT NULL 
               THEN IN_AD2.ADDRESS_LINE2
               ELSE IN_AD1.ADDRESS_LINE2 
       END AS BILL_ADDR2,
       CASE WHEN IN_AD2.CUSTOMER_NUM IS NOT NULL 
               THEN IN_AD2.ADDRESS_LINE3
               ELSE IN_AD1.ADDRESS_LINE3 
       END AS BILL_TO_CITY,
       CASE WHEN IN_AD2.CUSTOMER_NUM IS NOT NULL 
               THEN IN_AD2.ADDRESS_LINE4
               ELSE IN_AD1.ADDRESS_LINE4 
       END AS BILL_TO_STATE,
       CASE WHEN IN_AD2.CUSTOMER_NUM IS NOT NULL 
               THEN IN_AD2.ADDRESS_LINE5
               ELSE IN_AD1.ADDRESS_LINE5 
       END AS BILL_TO_ZIP

  FROM GCPS.OL_QUOTE_HEADER AS O_Q_HEADER 
  JOIN GCPS.OFFER_LETTER AS O_LETTER
    ON O_LETTER.COUNTRY_CODE = O_Q_HEADER.COUNTRY_CODE 
   AND O_LETTER.QUOTE_NUM = O_Q_HEADER.QUOTE_NUM
   AND O_LETTER.QUOTE_VERSION_NUM = O_Q_HEADER.QUOTE_VERSION_NUM
   
  JOIN GCPS.INVOICE_HEADER AS IN_HE
    ON IN_HE.COUNTRY_CODE = O_LETTER.COUNTRY_CODE
   AND IN_HE.OFFER_LETTER_NUM = O_LETTER.OFFER_LETTER_NUM
   AND IN_HE.DEBIT_CREDIT_INDC = 'DB' 
       
   JOIN GCPS.INVOICE_DETAIL AS IN_DE
     ON IN_DE.COUNTRY_CODE = IN_HE.COUNTRY_CODE
    AND IN_DE.INVOICE_SEQ_NUM = IN_HE.INVOICE_SEQ_NUM
   
   JOIN GCPS.INVOICE_ADDRESS AS IN_AD1
     ON IN_AD1.COUNTRY_CODE = IN_DE.COUNTRY_CODE
    AND IN_AD1.INVOICE_SEQ_NUM = IN_DE.INVOICE_SEQ_NUM
    AND IN_AD1.ADDRESS_TYPE = 'S'
    
   LEFT JOIN GCPS.INVOICE_ADDRESS AS IN_AD2
     ON IN_AD2.COUNTRY_CODE = IN_AD1.COUNTRY_CODE
    AND IN_AD2.INVOICE_SEQ_NUM = IN_AD1.INVOICE_SEQ_NUM   
    AND IN_AD2.ADDRESS_TYPE = 'B'

  WHERE O_Q_HEADER.COUNTRY_CODE = 'CA'
    AND O_Q_HEADER.ENTERPRISE_NUM = '153804570'
    AND IN_HE.LAST_UPDATE_TIMESTAMP > '2019-07-24 18:03:52.000000'
    AND (IN_DE.MFR_SERIAL_NUM is not null AND rtrim(IN_DE.MFR_SERIAL_NUM) != '') 